spring:
  datasource:
    url: jdbc:mysql://1.237.109.32:3306/saDB
    username: seongwop
    password: Xovnd7863
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
