spring:
  profiles:
    include: secret
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

logging:
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
  level:
    org:
      springframework:
        batch: DEBUG
