spring:
  profiles:
    include: secret
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error